# The numpy.random in Python

The use of randomness is an important of the configuration and evaluation of machine learning algorithms.  The splitting of data into random train and test sets, generating random numbers and harnessing randomness.  Python use a popular and robust pesudorandom number generator called the Mersenne  Twister.  The pesudorandom number generator is a mathematical function that generates a sequence of nearly numbers.

In [4]:
# Simple Random data example


# The rand function will generate random number between 0 and 1 and number 4 and 2 is 3 rows and 2 coloumn arrays
import numpy as np
np.random.rand(3,2)

array([[0.18869931, 0.08629787],
       [0.98449246, 0.09770264],
       [0.61508337, 0.97315286]])

In [5]:
# Returns The matrix of random values drawn from the standard normal distribution.
#np.random.randn(2,2)
2.5 * np.random.randn(2, 4) + 3

array([[ 2.78434046, -0.72191917,  4.87240269,  1.98815216],
       [ 1.63035423,  2.45351544,  7.77228026,  0.89418041]])

# Simple Random Data

A simple random sample is a subset of individuals (a sample) chosen from a larger set (a population). Each individual is chosen randomly and entirely by chance, such that each individual has the same probability of being chosen at any stage during the sampling process, and each subset of k individuals has the same probability of being chosen for the sample as any other subset of k individuals.  This process and technique is known as simple random sampling. A simple random sample is an unbiased surveying technique.

In [6]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The above code Return random integers from low (inclusive) to high (exclusive).

In [9]:
np.random.random_sample((5,))

array([0.17934579, 0.15071245, 0.22397887, 0.20533532, 0.47764807])

The above code return random floats in the half-open interval [0.0, 1.0).

# Permutation
A random permutation is a random ordering of a set of objects, that is, a permutation-valued random variable. The use of random permutations is often fundamental to fields that use randomized algorithms such as coding theory, cryptography, and simulation. A good example of a random permutation is the shuffling of a deck of cards: this is ideally a random permutation of the 52 cards.

In [14]:
np.random.permutation(10)

array([7, 4, 6, 2, 5, 8, 1, 9, 3, 0])

The above code randomly permute a sequence

In [19]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

The above code randomly arranging 0 to 9 as a array of 3 rows and 3 column

# The Bionomial distribution

The word “binomial” means “two numbers.” A binomial distribution for a random variable X is one in which there are only two possible outcomes, pass and fail, for a finite number of trials.  An example involves rolling a standard 6-sided die. Let’s say that we hope to roll a five. In this case, we define success as “rolling a 5” and failure as “not rolling a 5.” In this case, each roll of the die would be a trial.

For the binomial distribution to be applied, each successive trial must be independent of the last; that is, the outcome of a previous trial has no bearing on the probabilities of success on subsequent trials. For the roll of a die, we know this to be true: just because a five rolled the last time does not change the probability of rolling a 5 on future rolls; the probability of success remains unchanged at 1 in 6.

A real world example. A company drills 9 wild-cat oil exploration wells, each with an estimated probability of success of 0.1. All nine wells fail. What is the probability of that happening?

Let’s do 20,000 trials of the model, and count the number that generate zero positive results.

In [22]:
sum(np.random.binomial(9, 0.1, 20000) == 0)/20000

0.38845

The above example the probablity of all 9 wells fail is 38%